---
- name: Install Logrotate.
  apt:
    name: logrotate
    state: present

- name: Generate logrotate main configuration file
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure logrotate configuration directory
  file:
    path: "{{ logrotate_include_dir }}"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Generate service log rotation configuration
  template:
    src: service.j2
    dest: '{{ logrotate_include_dir }}/{{ service_logs.name }}'
    owner: root
    group: root
    mode: '0644'
    validate: logrotate -d %s
  with_items: '{{ logrotate_service_logs }}'
  loop_control:
    loop_var: service_logs
    label: "{{ service_logs.name | default('') }}"
  when:  logrotate_service_logs | length > 0 and service_logs.name | default('') and service_logs.logs | default([]) | length > 0
